# Generated by Django 2.1.2 on 2019-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiarc_registration', '0002_auto_20190112_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiarcuser',
            name='blog_url',
            field=models.CharField(blank=True, max_length=20, verbose_name='blog_url'),
        ),
        migrations.AddField(
            model_name='hiarcuser',
            name='boj_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='boj_id'),
        ),
        migrations.AddField(
            model_name='hiarcuser',
            name='codeforces_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='codeforces_id'),
        ),
        migrations.AddField(
            model_name='hiarcuser',
            name='github_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='github_id'),
        ),
    ]
